package com.campusfix.common.storage;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;

/**
 * Files on the machine's own disk. The default, so a fresh clone runs with no
 * cloud account, no credentials and no Docker.
 *
 * <p>Known limits, and they are the reason {@link S3FileStorage} exists: the
 * folder does not survive a container being replaced unless it is mounted as a
 * volume, and two instances of the application would each see only their own
 * uploads.
 */
@Component
@Profile("!s3")
public class LocalFileStorage implements FileStorage {

    private static final Logger log = LoggerFactory.getLogger(LocalFileStorage.class);

    private final Path root;

    public LocalFileStorage(StorageProperties properties) {
        this.root = Path.of(properties.location()).toAbsolutePath().normalize();
        try {
            Files.createDirectories(root);
        } catch (IOException e) {
            throw new StorageException("Could not create the upload folder at " + root, e);
        }
        log.info("Attachments are stored on disk at {}", root);
    }

    @Override
    public void store(String key, InputStream content, long size, String contentType) {
        Path target = resolve(key);
        try {
            Files.createDirectories(target.getParent());
            Files.copy(content, target, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            throw new StorageException("Could not save the file", e);
        }
    }

    @Override
    public InputStream retrieve(String key) {
        Path source = resolve(key);
        if (!Files.exists(source)) {
            throw new StorageException("The stored file is missing: " + key);
        }
        try {
            return Files.newInputStream(source);
        } catch (IOException e) {
            throw new StorageException("Could not read the file", e);
        }
    }

    @Override
    public void delete(String key) {
        try {
            Files.deleteIfExists(resolve(key));
        } catch (IOException e) {
            throw new StorageException("Could not delete the file", e);
        }
    }

    @Override
    public String describe() {
        return "local disk at " + root;
    }

    /**
     * Turns a key into a real path and refuses anything that escapes the root.
     *
     * <p>Keys are generated by the service and never come from a user, so this
     * should be impossible. It is here anyway: path traversal is the classic
     * upload vulnerability, and a check that costs nothing should not depend on
     * every future caller remembering the rule.
     */
    private Path resolve(String key) {
        Path candidate = root.resolve(key).normalize();
        if (!candidate.startsWith(root)) {
            throw new StorageException("Rejected a storage key that points outside the upload folder: " + key);
        }
        return candidate;
    }
}
